name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Connect to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop the running container
            docker stop thirsty_feistel || true
            docker rm thirsty_feistel || true

            # Pull the latest image
            docker pull cookielover202/flask-app:latest

            # Run the container
            docker run -d -p 5000:5000 --name thirsty_feistel cookielover202/flask-app:latest
          EOF

